sudo: required
language: node_js
node_js:
  - "10"
before_script:
  - npm install
  - npm run build
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
script:
  - npm run test-travis